export const DEFAULT_SECURITY_HEADERS = {
  "X-Frame-Options": "deny",
  "X-XSS-Protection": "1; mode=block",
  "X-Content-Type-Options": "nosniff",
  "Content-Security-Policy": "default-src 'none'; img-src data:; media-src *; style-src 'unsafe-inline'",
  "Strict-Transport-Security" : "max-age=31536000; includeSubDomains",
  "Permissions-Policy": 'interest-cohort=()'
}

export type TWarpPipeConfiguration = {
  key: string,
  hostname: string,
  userAgent: string,
  headers: { [key:string]: string }
  maxRedirects: number
  keepAlive: boolean
  socketTimeout: number
  contentLengthLimit?: number,
  mimeTypes: string[]
}

export const DEFAULT_CONFIGURATION : TWarpPipeConfiguration = {
  key: '0x24FEEDFACEDEADBEEFCAFE',
  hostname: 'localhost',
  userAgent: 'WarpPipe',
  headers: DEFAULT_SECURITY_HEADERS,
  maxRedirects: 4,
  keepAlive: true,
  socketTimeout: 10,
  //contentLengthLimit: 5242880,
  mimeTypes: [
    "video/mp4",
    "image/bmp",
    "image/cgm",
    "image/g3fax",
    "image/gif",
    "image/ief",
    "image/jp2",
    "image/jpeg",
    "image/jpg",
    "image/pict",
    "image/png",
    "image/prs.btif",
    "image/svg+xml",
    "image/tiff",
    "image/vnd.adobe.photoshop",
    "image/vnd.djvu",
    "image/vnd.dwg",
    "image/vnd.dxf",
    "image/vnd.fastbidsheet",
    "image/vnd.fpx",
    "image/vnd.fst",
    "image/vnd.fujixerox.edmics-mmr",
    "image/vnd.fujixerox.edmics-rlc",
    "image/vnd.microsoft.icon",
    "image/vnd.ms-modi",
    "image/vnd.net-fpx",
    "image/vnd.wap.wbmp",
    "image/vnd.xiff",
    "image/webp",
    "image/x-cmu-raster",
    "image/x-cmx",
    "image/x-icon",
    "image/x-macpaint",
    "image/x-pcx",
    "image/x-pict",
    "image/x-portable-anymap",
    "image/x-portable-bitmap",
    "image/x-portable-graymap",
    "image/x-portable-pixmap",
    "image/x-quicktime",
    "image/x-rgb",
    "image/x-xbitmap",
    "image/x-xpixmap",
    "image/x-xwindowdump",
    "audio/wav",
    "audio/x-wav",
    "audio/x-pn-wave",
    "audio/ogg",
    "audio/mpeg",
    "audio/mp3",
    "audio/webm",
    "audio/flac",
    "audio/aac",
    "audio/wave",
    "audio/aac",
    "audio/m4a",
    "audio/x-m4a",
    "audio/mp4",
    "audio/3gpp",
    "video/x-ms-asf",
    "video/mp4",
    "video/quicktime",
    "video/webm",
    "video/ogg"
  ]
} 